version: 2
updates:
  - package-ecosystem: pip
    directory: '/requirements'
    schedule:
      interval: weekly
    open-pull-requests-limit: 20
    labels:
      - Backend
      - dependencies
  - package-ecosystem: docker
    directory: '/'
    schedule:
      interval: weekly
    open-pull-requests-limit: 20
    labels:
      - Backend
      - dependencies
