# Global excludes, override per repo below if different excludes required.
exclude: >
  (?x)^(
    docs
    | node_modules
    | assets
    | static
    | bedrock/externalfiles/files_cache
    | git-repos
  )
repos:
  # Note: hooks that add content must run before ones which check formatting, lint, etc
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: check-shebang-scripts-are-executable
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
        args:
          - --markdown-linebreak-ext=md
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.4.2
    hooks:
    -   id: insert-license
        language: python
        files: \.py$
        args:
          - --license-filepath
          - license_header/mpl2_header.txt
          - --comment-style
          - "|#|"
    -   id: insert-license
        exclude: media\/.*\/libs\/.*$
        files: \.js$
        args:
          - --license-filepath
          - license_header/mpl2_header.txt
          - --comment-style
          - /*|*|*/
    -   id: insert-license
        files: \.scss$
        args:
          - --license-filepath
          - license_header/mpl2_header.txt
          - --comment-style
          - //
    -   id: insert-license
        files: \.sh$
        args:
          - --license-filepath
          - license_header/mpl2_header.txt
    -   id: insert-license
        files: \.html$  # jinja2
        args:
          - --license-filepath
          - license_header/mpl2_header.txt
          - --comment-style
          - '{#||#}'
    -   id: insert-license
        files: \.ftl$  # fluent templates
        args:
          - --license-filepath
          - license_header/mpl2_header.txt
          - --comment-style
          - "|#|"
  - repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
      - id: black
        language_version: python3
  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.258
    hooks:
      - id: ruff
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.7.1
    hooks:
      - id: prettier
  #        TODO Remove this once we migrate to 3.0.0
  #        See https://github.com/pre-commit/mirrors-prettier/issues/29
        files: \.js$
        additional_dependencies:
          - prettier@2.8.1
  - repo: https://github.com/awebdeveloper/pre-commit-stylelint
    rev: 0.0.2
    hooks:
      - id: stylelint
        additional_dependencies:
          - "stylelint@15.6.0"
          - "stylelint-config-standard-scss@9.0.0"
          - "postcss-scss@4.0.2"
          - "postcss@8.3.11"
  - repo: https://github.com/eslint/eslint
    rev: v8.31.0
    hooks:
      - id: eslint
        additional_dependencies:
          - "eslint-plugin-json@3.1.0"
          - "eslint-config-prettier@8.6.0"
  #       Additional excludes in /.eslintignore file
