sudo: false
language: python
python:
  - "2.7"
node_js:
  - "0.12"
branches:
  only:
    - master
cache:
  directories:
    - $HOME/.cache/pip
    - node_modules
before_script:
  - flake8 bedrock lib
  - python manage.py runscript check_calendars
  - mysql -e 'create database bedrock_test;'
  - python manage.py version
  - python manage.py migrate --noinput
  - python manage.py collectstatic --noinput -v 0
  - travis_retry python manage.py update_product_details
  - travis_retry svn checkout https://svn.mozilla.org/projects/mozilla.com/trunk/locales/ locale
  - travis_retry npm install
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script:
  - grunt test
  - python manage.py test
  - py.test test_redirects -n auto
before_install:
  - travis_retry git submodule update --init --recursive
install:
  - travis_retry python bin/peep.py install -r requirements/pip.txt --no-use-wheel
  - travis_retry python bin/peep.py install -r requirements/dev.txt --no-use-wheel
  - travis_retry python bin/peep.py install -r requirements/prod.txt --no-use-wheel
  - travis_retry python bin/peep.py install -r requirements/test_redirects.txt --no-use-wheel
notifications:
  irc:
    channels:
      - "irc.mozilla.org#www"
    on_success: change
    on_failure: always
    use_notice: true
addons:
  firefox: "35.0"
