sudo: false
language: python
python:
  - "2.7"
env:
  global:
    - PIP_DOWNLOAD_CACHE="pip_cache"
branches:
  only:
    - master
cache:
  directories:
    - pip_cache
before_script:
  - flake8 bedrock lib
  - mysql -e 'create database bedrock_test;'
  - python manage.py version
  - python manage.py syncdb --noinput --migrate
  - python manage.py collectstatic --noinput -v 0
  - python manage.py update_product_details
  - svn checkout https://svn.mozilla.org/projects/mozilla.com/trunk/locales/ locale
script: coverage run manage.py test
before_install:
  - git submodule update --init --recursive
install:
  - pip install -r requirements/dev.txt
after_success:
  - pip install coveralls
  - coveralls
notifications:
  irc:
    channels:
      - "irc.mozilla.org#www"
    on_success: change
    on_failure: always
    use_notice: true
