# All files translated by the community by at least some locales should
# be covered by the [[paths]] in this file.

basepath = ".."

locales = [
    "ach",
    "af",
    "am",
    "an",
    "ar",
    "ast",
    "az",
    "azz",
    "be",
    "bg",
    "bn",
    "br",
    "bs",
    "ca",
    "cak",
    "crh",
    "cs",
    "cy",
    "da",
    "de",
    "dsb",
    "el",
    "en-CA",
    "en-GB",
    "eo",
    "es-AR",
    "es-CL",
    "es-ES",
    "es-MX",
    "et",
    "eu",
    "fa",
    "ff",
    "fi",
    "fr",
    "fy-NL",
    "ga-IE",
    "gd",
    "gl",
    "gn",
    "gu-IN",
    "he",
    "hi-IN",
    "hr",
    "hsb",
    "hto",
    "hu",
    "hy-AM",
    "ia",
    "id",
    "is",
    "it",
    "ja",
    "ka",
    "kab",
    "kk",
    "km",
    "kn",
    "ko",
    "lij",
    "lo",
    "lt",
    "ltg",
    "lv",
    "mk",
    "ml",
    "mr",
    "ms",
    "my",
    "nb-NO",
    "ne-NP",
    "nl",
    "nn-NO",
    "nv",
    "oc",
    "pa-IN",
    "pai",
    "pbb",
    "pl",
    "pt-BR",
    "pt-PT",
    "qvi",
    "rm",
    "ro",
    "ru",
    "si",
    "sk",
    "sl",
    "son",
    "sq",
    "sr",
    "sv-SE",
    "sw",
    "ta",
    "te",
    "th",
    "tl",
    "tr",
    "trs",
    "uk",
    "ur",
    "uz",
    "vi",
    "wo",
    "xh",
    "zam",
    "zh-CN",
    "zh-TW",
    "zu",
]

[[paths]]
    reference = "en/*.ftl"
    l10n = "{locale}/*.ftl"
[[paths]]
    reference = "en/banners/**/*.ftl"
    l10n = "{locale}/banners/**/*.ftl"
[[paths]]
    reference = "en/firefox/*.ftl"
    l10n = "{locale}/firefox/*.ftl"
[[paths]]
    reference = "en/firefox/browsers/**/*.ftl"
    l10n = "{locale}/firefox/browsers/**/*.ftl"
[[paths]]
    reference = "en/firefox/features/**/*.ftl"
    l10n = "{locale}/firefox/features/**/*.ftl"
[[paths]]
    reference = "en/firefox/more/**/*.ftl"
    l10n = "{locale}/firefox/more/**/*.ftl"
[[paths]]
    reference = "en/firefox/new/**/*.ftl"
    l10n = "{locale}/firefox/new/**/*.ftl"
[[paths]]
    reference = "en/firefox/nightly/**/*.ftl"
    l10n = "{locale}/firefox/nightly/**/*.ftl"
[[paths]]
    reference = "en/firefox/privacy/book.ftl"
    l10n = "{locale}/firefox/privacy/book.ftl"
    locales = [
        "de",
        "fr"
    ]
[[paths]]
    reference = "en/firefox/privacy/passwords.ftl"
    l10n = "{locale}/firefox/privacy/passwords.ftl"
[[paths]]
    reference = "en/firefox/products/**/*.ftl"
    l10n = "{locale}/firefox/products/**/*.ftl"
[[paths]]
    reference = "en/firefox/retention/**/*.ftl"
    l10n = "{locale}/firefox/retention/**/*.ftl"
    locales = [
        "de",
        "es-ES",
        "fr",
        "id",
        "pl",
        "pt-BR",
        "ru",
        "zh-TW"
    ]
[[paths]]
    reference = "en/firefox/set-as-default/**/*.ftl"
    l10n = "{locale}/firefox/set-as-default/**/*.ftl"
[[paths]]
    reference = "en/firefox/welcome/**/*.ftl"
    l10n = "{locale}/firefox/welcome/**/*.ftl"
[[paths]]
    reference = "en/firefox/whatsnew/**/*.ftl"
    l10n = "{locale}/firefox/whatsnew/**/*.ftl"
[[paths]]
    reference = "en/mozorg/contribute.ftl"
    l10n = "{locale}/mozorg/contribute.ftl"
[[paths]]
    reference = "en/mozorg/home.ftl"
    l10n = "{locale}/mozorg/home.ftl"
[[paths]]
    reference = "en/mozorg/mission.ftl"
    l10n = "{locale}/mozorg/mission.ftl"
[[paths]]
    reference = "en/mozorg/about.ftl"
    l10n = "{locale}/mozorg/about.ftl"
[[paths]]
    reference = "en/mozorg/about/governance/policies/*.ftl"
    l10n = "{locale}/mozorg/about/governance/policies/*.ftl"
    locales = [
        "ar",
        "de",
        "es-ES",
        "fr",
        "hi-IN",
        "id",
        "it",
        "ja",
        "nl",
        "pl",
        "pt-BR",
        "ru",
        "zh-CN",
        "zh-TW",
    ]
[[paths]]
    reference = "en/mozorg/about/history.ftl"
    l10n = "{locale}/mozorg/about/history.ftl"
[[paths]]
    reference = "en/mozorg/about/legal.ftl"
    l10n = "{locale}/mozorg/about/legal.ftl"
[[paths]]
    reference = "en/mozorg/about/manifesto.ftl"
    l10n = "{locale}/mozorg/about/manifesto.ftl"
[[paths]]
    reference = "en/mozorg/about/shared.ftl"
    l10n = "{locale}/mozorg/about/shared.ftl"
[[paths]]
    reference = "en/mozorg/newsletters.ftl"
    l10n = "{locale}/mozorg/newsletters.ftl"
    locales = [
        "bg",
        "cs",
        "de",
        "es-ES",
        "fr",
        "hu",
        "id",
        "it",
        "nl",
        "pl",
        "pt-BR",
        "ru",
        "zh-TW",
    ]
[[paths]]
    reference = "en/newsletter/opt-out-confirmation.ftl"
    l10n = "{locale}/newsletter/opt-out-confirmation.ftl"
    locales = [
        "de",
        "es-ES",
        "fr",
        "id",
        "pl",
        "pt-BR",
        "ru"
    ]
[[paths]]
    reference = "en/privacy/*.ftl"
    l10n = "{locale}/privacy/*.ftl"
[[paths]]
    reference = "en/products/vpn/platforms/*.ftl"
    l10n = "{locale}/products/vpn/platforms/*.ftl"
[[paths]]
    reference = "en/products/vpn/landing.ftl"
    l10n = "{locale}/products/vpn/landing.ftl"
[[paths]]
    reference = "en/products/vpn/shared.ftl"
    l10n = "{locale}/products/vpn/shared.ftl"
